### ISSUE TITLE
full support for Canvas inside Web Worker?

### ISSUE THREAD

**Issue by joe312213** [jtenner/e2d#5]
Hi,

Is it possible, or feasible to create a Canvas, get its context and do some rendering all inside a web worker (then send the data back to the main thread via canvas.toDataURL(), or such like), using e2d?

(I'm using a js lib for morphing images which uses canvas (morpher-js), but it's a bit slow for smooth animation, so I'm using it to create a cache of between images which I'm then blending using another canvas, but the pre-comp is obviously still blocking the main thread. So I want to shift it all off to a web worker if possible.)

I saw in Canvas.js that the Renderer is set to null if inside a worker, so I'm guessing using canvas in this way is not currently possible, unless I'm missing something..

**Comment by jtenner** [comment]
Hi.  The code that does the rendering is here:

Line 45 of Canvas.js:
```javascript
if (isWorker) {
    postMessage({ type: 'canvas', value: { id: this.id, width: this.width, height: this.height, children: result } });
  } else {
    this.renderer.render(result);
    this.fillPattern = this.renderer.ctx.createPattern(this.renderer.canvas, 'no-repeat');
  }
```
Two things are happening.

The worker determines the draw logic, and the browser does the actual drawing.  The truth is it's hard to do image manipulation inside a web worker.  Until someone can actually code a canvas 2d context inside a web worker, we must rely on the main thread to do drawing.

To help you with your problem: You don't have access to the pixels exactly from the web worker.

If you think there is a use case for getting the drawn pixels and doing a manipulation inside a worker, I could probably help you with that.

Cheers,
-Josh

**Comment by joe312213** [comment]
Thanks Josh.

I think I broadly understand how to transfer ctx.getImageData to workers using transferable objects (to  save copying), do the processing in worker, then send back to the main thread be put in the canvas and drawn again.

But I'm not too sure how to use e2d to make that job easier.

**Comment by jtenner** [comment]
I forgot about transferables!  I use structured cloning, so I don't have an API that makes it simple.

Easy peasy, though!

browser side:
```javascript
renderer.worker.postMessage({
  type: 'message-type', //choose something very unique here
  value: data
}, [data]);
```

worker side:
```javascript
renderer.on('message-type', function(data) {

//call postMessage({ type: 'message-type-result', value: whatever });
});
```

**Comment by jtenner** [comment]
Also, I suppose an API addition is in order:

```javascript
r.getImageData(width, height, function(imageData) {
   //{ width: width, height: height, data: Uint8ClampedArray }
});
//or
r.getImageData(sx, sy, width, height, function(imageData) {
  
});
```

**Comment by jtenner** [comment]
@joe312213 I think I would be happy to implement the following functions for you!

Also, I suppose an API addition is in order:
```javascript
r.getImageData(width, height, function(imageData) {
   //{ width: width, height: height, data: Uint8ClampedArray }
});
//or
r.getImageData(sx, sy, width, height, function(imageData) {
  //this is the easy part
});
```

Probably followed up by the dream API:

```javascript
r.render(
  e2d.putImageData(UintClampedArray), //dx and dy default to 0
  e2d.putImageData(data, dx, dy),
  e2d.putImageData(data, dx, dy, dirtyX, dirtyY, dirtyWidth, dirtyHeight)
);
```

The problem with using this method is that it slows down the process because of structured cloning.

I might have to implement a new class for this to prevent the slow down.

Proposed new API example
```javascript
r.getImageData(params..., function(imageData) {
   //imageData.constructor === e2d.ImageData
   //imageData is referenced on the browser side and must be cached/disposed
   imageData.cache();
   var data = imageData.data;

   for(var i = 0; i < data.length; i += 4) {
      //do some manipulation the array
   }
   imageData.save();
   r.render(
     e2d.putImageData(imageData, ...params)
  );
  imageData.dispose();
})
```

**Comment by jtenner** [comment]
@joe312213 

I wanted to answer one final question, because I already gave you the ability to create offscreen canvases using the Canvas constructor.

```javascript
var offscreenCanvas = e2d.Canvas.create(width, height).cache();

offscreenCanvas.render(
  //e2d commands
);

var img = offscreenCanvas.toImage(); //exports the canvas to a png and stores it in Img object

r.render(
   e2d.drawCanvas(offscreenCanvas)
);
```

**Comment by joe312213** [comment]
Hi Josh,

Thank you for all the options. Very kind of you to take the time!

I've made a closer study of the morphing script and from what I can tell, due to its complexity there's no straightforward way (for me) of adapting it to put enough of its work into a worker to prevent noticeable main thread slowdown. So I think on this occasion I will do the processing offline and probably use a video element :)

I will keep a close eye on your rendering engine for future use though, thanks again!

**Comment by jtenner** [comment]
It seems like I don't understand what your needs are. I probably should implement getImageData and putImageData though as a side project.

**Comment by jtenner** [comment]
I assume I am unable to help with this issue.  I would be more than happy to reopen the issue and put in some work, but it seems unnecessary right now.

Cheers,
-Josh

**Comment by jtenner** [comment]
Hey @joe312213, I have removed support for canvas inside a web worker and was curious what happened with your project?

Thanks,
-Josh

**Comment by joe312213** [comment]
Hi Josh,

Thanks for your message, and interest in my project. I found even with
better operating multi-threading, the JS code I was using would still
likely introduce unacceptable delays in the UX. So I went a different route
and used some video sections for my animation instead.

Regards,
Joe


On 18 March 2016 at 17:47, jtenner <notifications@github.com> wrote:

> Hey @joe312213 <https://github.com/joe312213>, I have removed support for
> canvas inside a web worker and was curious what happened with your project?
>
> Thanks,
> -Josh
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jtenner/e2d/issues/5#issuecomment-198468165>
>



-- 
-----------------------------------------------------------------------------------------------

http://joe-hudson.blogspot.co.uk
http://littlecog.net <http://pepol.net>
http://pepol.net
http://www.tangolingua.com


---------------------------------------
